import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        display: ["'Outfit'", "sans-serif"],
        serif: ["'Inter'", "sans-serif"],
        sans: ["'Inter'", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        crimson: { DEFAULT: "hsl(var(--crimson))", soft: "hsl(var(--crimson-soft))" },
        lettuce: { DEFAULT: "hsl(var(--lettuce))", soft: "hsl(var(--lettuce-soft))" },
        mint:    "hsl(var(--mint))",
        lavender: { DEFAULT: "hsl(var(--lavender))", deep: "hsl(var(--lavender-deep))", soft: "hsl(var(--lavender-soft))" },
        silver:  "hsl(var(--silver))",
        pearl:   "hsl(var(--pearl))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 8px)",
        sm: "calc(var(--radius) - 12px)",
      },
      backgroundImage: {
        "gradient-pulse":   "var(--gradient-pulse)",
        "gradient-grid":    "var(--gradient-grid)",
        "gradient-mist":    "var(--gradient-mist)",
        "gradient-divider": "var(--gradient-divider)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        soft: "var(--shadow-soft)",
        crimson: "var(--shadow-glow-crimson)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in-up":     { from: { opacity: "0", transform: "translateY(16px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "float-soft":     { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-10px)" } },
        "spin-slow":      { to: { transform: "rotate(360deg)" } },
        "marquee":        { from: { transform: "translateX(0)" }, to: { transform: "translateX(-50%)" } },
        "vein-flow":      { "0%": { transform: "translateX(-20%)", opacity: "0" }, "20%": { opacity: "0.6" }, "100%": { transform: "translateX(120%)", opacity: "0" } },
        "pulse-ring":     { "0%": { transform: "scale(0.85)", opacity: "0.7" }, "100%": { transform: "scale(1.4)", opacity: "0" } },
        "rocket-launch":  { "0%": { transform: "translateY(120vh) translateX(-20vw) scale(0.5)", opacity: "0" }, "10%": { opacity: "1" }, "90%": { opacity: "1" }, "100%": { transform: "translateY(-120vh) translateX(20vw) scale(1)", opacity: "0" } },
        "drone-patrol":   { "0%, 100%": { transform: "translateX(0) translateY(0)" }, "25%": { transform: "translateX(15vw) translateY(-5vh)" }, "50%": { transform: "translateX(5vw) translateY(10vh)" }, "75%": { transform: "translateX(-10vw) translateY(5vh)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in-up": "fade-in-up 0.9s cubic-bezier(.2,.8,.2,1) both",
        "float-soft": "float-soft 6s ease-in-out infinite",
        "spin-slow": "spin-slow 24s linear infinite",
        "marquee": "marquee 38s linear infinite",
        "vein-flow": "vein-flow 9s ease-in-out infinite",
        "pulse-ring": "pulse-ring 2.4s cubic-bezier(.2,.8,.2,1) infinite",
        "rocket-launch": "rocket-launch 20s linear infinite",
        "drone-patrol": "drone-patrol 25s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
